### ISSUE TITLE
Why not....?

### ISSUE THREAD

**Issue by ic-it** [anijackich/kinescope-dl#1]
+ Why not `click` for cli?
+ Why not `loguru` for logging? 
+ Why so much magic context? Yes, you put some of the magic into constants, but where is the separation into methods? 
+ Why no versions in `requirements.txt` ?
+ Why don't you use `tempfile` for temporary files?

**Comment by anijackich** [comment]
Thank you for your feedback! I will definitely take your advice into account at further stages of development.
